CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|P35569|IRS1_MOUSE      MASPPDTDGFSDVRKVGYLRKPKSMHKRFFVLRAASEAGGPARLEYYENEKKWRHKSSAP
sp|P35568|IRS1_HUMAN      MASPPESDGFSDVRKVGYLRKPKSMHKRFFVLRAASEAGGPARLEYYENEKKWRHKSSAP
                          *****::*****************************************************

sp|P35569|IRS1_MOUSE      KRSIPLESCFNINKRADSKNKHLVALYTRDEHFAIAADSEAEQDSWYQALLQLHNRAKAH
sp|P35568|IRS1_HUMAN      KRSIPLESCFNINKRADSKNKHLVALYTRDEHFAIAADSEAEQDSWYQALLQLHNRAKGH
                          **********************************************************.*

sp|P35569|IRS1_MOUSE      HDGA----GGGCGGSCSGSSGVGEAGEDLSY-DTGPGPAFKEVWQVILKPKGLGQTKNLI
sp|P35568|IRS1_HUMAN      HDGAAALGAGGGGGSCSGSSGLGEAGEDLSYGDVPPGPAFKEVWQVILKPKGLGQTKNLI
                          ****    .** *********:********* *. *************************

sp|P35569|IRS1_MOUSE      GIYRLCLTSKTISFVKLNSEAAAVVLQLMNIRRCGHSENFFFIEVGRSAVTGPGEFWMQV
sp|P35568|IRS1_HUMAN      GIYRLCLTSKTISFVKLNSEAAAVVLQLMNIRRCGHSENFFFIEVGRSAVTGPGEFWMQV
                          ************************************************************

sp|P35569|IRS1_MOUSE      DDSVVAQNMHETILEAMRAMSDEFRPRSKSQSSSSCSNPISVPLRRHHLNNPPPSQVGLT
sp|P35568|IRS1_HUMAN      DDSVVAQNMHETILEAMRAMSDEFRPRSKSQSSSNCSNPISVPLRRHHLNNPPPSQVGLT
                          **********************************.*************************

sp|P35569|IRS1_MOUSE      RRSRTESITATSPASMVGGKPGSFRVRASSDGEGTMSRPASVDGSPVSPSTNRTHAHRHR
sp|P35568|IRS1_HUMAN      RRSRTESITATSPASMVGGKPGSFRVRASSDGEGTMSRPASVDGSPVSPSTNRTHAHRHR
                          ************************************************************

sp|P35569|IRS1_MOUSE      GSSRLHPPLNHSRSIPMPSSRCSPSATSPVSLSSSSTSGHGSTSDCLFPRRSSASVSGSP
sp|P35568|IRS1_HUMAN      GSARLHPPLNHSRSIPMPASRCSPSATSPVSLSSSSTSGHGSTSDCLFPRRSSASVSGSP
                          **:***************:*****************************************

sp|P35569|IRS1_MOUSE      SDGGFISSDEYGSSPCDFRSSFRSVTPDSLGHTPPARGEEELSNYICMGGKGASTLAAPN
sp|P35568|IRS1_HUMAN      SDGGFISSDEYGSSPCDFRSSFRSVTPDSLGHTPPARGEEELSNYICMGGKGPSTLTAPN
                          ****************************************************.***:***

sp|P35569|IRS1_MOUSE      GHYILSRGGNGHRYIPGANLGTSPALPGDEAAGAADLDNRFRKRTHSAGTSPTISHQKTP
sp|P35568|IRS1_HUMAN      GHYILSRGGNGHRCTPGTGLGTSPALAGDEAASAADLDNRFRKRTHSAGTSPTITHQKTP
                          *************  **:.*******.*****.*********************:*****

sp|P35569|IRS1_MOUSE      SQSSVASIEEYTEMMPAAYPPGGGSGGRLPGYRHSAFVPTHSYPEEGLEMHHLERRGGHH
sp|P35568|IRS1_HUMAN      SQSSVASIEEYTEMMP-AYPPGGGSGGRLPGHRHSAFVPTRSYPEEGLEMHPLERRGGHH
                          **************** **************:********.********** ********

sp|P35569|IRS1_MOUSE      RPDTSNLHTDDGYMPMSPGVAPVPSNRKGNGDYMPMSPKSVSAPQQIINPIRRHPQRVDP
sp|P35568|IRS1_HUMAN      RPDSSTLHTDDGYMPMSPGVAPVPSGRKGSGDYMPMSPKSVSAPQQIINPIRRHPQRVDP
                          ***:*.*******************.***.******************************

sp|P35569|IRS1_MOUSE      NGYMMMSPSGSCSPDIGGG-SSSSSSISAAPSGSSYGKPWTNGVGGHHTHALPHAKPPVE
sp|P35568|IRS1_HUMAN      NGYMMMSPSGGCSPDIGGGPSSSSSSSNAVPSGTSYGKLWTNGVGGHHSHVLPHPKPPVE
                          **********.******** ****** .*.***:**** *********:*.***.*****

sp|P35569|IRS1_MOUSE      SGGGKLLPCTGDYMNMSPVGDSNTSSPSECYYGPEDPQHKPVLSYYSLPRSFKHTQRPGE
sp|P35568|IRS1_HUMAN      SSGGKLLPCTGDYMNMSPVGDSNTSSPSDCYYGPEDPQHKPVLSYYSLPRSFKHTQRPGE
                          *.**************************:*******************************

sp|P35569|IRS1_MOUSE      PEEGARHQHLRLSSSSGRLRYTATAEDSSSSTSSDSLGGGYCGARPESSLTHPHHHVLQP
sp|P35568|IRS1_HUMAN      PEEGARHQHLRLSTSSGRLLYAATADDSSSSTSSDSLGGGYCGARLEPSLPHPHHQVLQP
                          *************:***** *:***:******************* *.**.****:****

sp|P35569|IRS1_MOUSE      HLPRKVDTAAQTNSRLARPTRLSLGDPKASTLPRVREQQQQQQSSLHPPEPKSPGEYVNI
sp|P35568|IRS1_HUMAN      HLPRKVDTAAQTNSRLARPTRLSLGDPKASTLPRAREQQQQQQPLLHPPEPKSPGEYVNI
                          **********************************.********. ***************

sp|P35569|IRS1_MOUSE      EFGSGQPGYLAGPATSRSSPSVRCPPQLHPAPR-EETGSEEYMNMDLGPGRRATWQESGG
sp|P35568|IRS1_HUMAN      EFGSDQSGYLSGPVAFHSSPSVRCPSQLQPAPREEETGTEEYMKMDLGPGRRAAWQESTG
                          ****.*.***:**.: .********.**:**** ****:****:*********:**** *

sp|P35569|IRS1_MOUSE      VELGRIGPAPPGSATVCRPTRSVPNSRGDYMTMQIGCPRQSYVDTSPVAPVSYADMRTGI
sp|P35568|IRS1_HUMAN      VEMGRLGPAPPGAASICRPTRAVPSSRGDYMTMQMSCPRQSYVDTSPAAPVSYADMRTGI
                          **:**:******:*::*****:**.*********:.***********.************

sp|P35569|IRS1_MOUSE      AAEKASLPRPTGAAPPPSSTASSSASVTPQGATAEQATHSSLLGGPQGPGGMSAFTRVNL
sp|P35568|IRS1_HUMAN      AAEEVSLPRATMAAASSSSAASASPT-GPQGA-AELAAHSSLLGGPQGPGGMSAFTRVNL
                          ***:.****.* **...**:**:*.:  **** ** *:**********************

sp|P35569|IRS1_MOUSE      SPNHNQSAKVIRADTQGCRRRHSSETFS---APTRAGNTVPFGAGAAVGGSGGGGGGGSE
sp|P35568|IRS1_HUMAN      SPNRNQSAKVIRADPQGCRRRHSSETFSSTPSATRVGNTVPFGAGAAVGG-GGGSSSSSE
                          ***.**********.*************   :.**.************** ***....**

sp|P35569|IRS1_MOUSE      DVKRHSSASFENVWLRPGDLGGVSKESAPVCGAAGGLEKSLNYIDLDLAKEH---SQDCP
sp|P35568|IRS1_HUMAN      DVKRHSSASFENVWLRPGELGGAPKEPAKLCGAAGGLENGLNYIDLDLVKDFKQCPQECT
                          ******************:***..**.* :********:.********.*:.   .*:*.

sp|P35569|IRS1_MOUSE      SQQQSLPPPPPHQPLGSNEGNSPRRSSEDLSNYASISFQKQPEDRQ
sp|P35568|IRS1_HUMAN      PEPQPPPPPPPHQPLGSGESSSTRRSSEDLSAYASISFQKQPEDRQ
                          .: *. ***********.*..*.******** **************
